services: 
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    image:
      otho/r-py-vscode
    env_file:
      - .env
    volumes:
      - "${WORKING_DIR}:/project"
      - "${RENV_CACHE_PATH}:/root/.cache/R/renv/"
    tty: true
    working_dir:
      /project
    command: 
      bash -c "R --vanilla -s -e 'renv::restore()' &&
      tail -F anything"
